/*
 * Vero API
 *
 * All your money are belong to us
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lassi.patanen@gofore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vero.Api.Codegen.Client.OpenAPIDateConverter;

namespace Vero.Api.Codegen.Model
{
    /// <summary>
    /// PostUsersUserIdTaxCardsTaxCardIdRequest
    /// </summary>
    [DataContract(Name = "post_users_userId_tax_cards_taxCardId_request")]
    public partial class PostUsersUserIdTaxCardsTaxCardIdRequest : IEquatable<PostUsersUserIdTaxCardsTaxCardIdRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostUsersUserIdTaxCardsTaxCardIdRequest" /> class.
        /// </summary>
        /// <param name="taxCard">taxCard.</param>
        public PostUsersUserIdTaxCardsTaxCardIdRequest(TaxCard taxCard = default(TaxCard))
        {
            this.TaxCard = taxCard;
        }

        /// <summary>
        /// Gets or Sets TaxCard
        /// </summary>
        [DataMember(Name = "taxCard", EmitDefaultValue = false)]
        public TaxCard TaxCard { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostUsersUserIdTaxCardsTaxCardIdRequest {\n");
            sb.Append("  TaxCard: ").Append(TaxCard).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PostUsersUserIdTaxCardsTaxCardIdRequest);
        }

        /// <summary>
        /// Returns true if PostUsersUserIdTaxCardsTaxCardIdRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of PostUsersUserIdTaxCardsTaxCardIdRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PostUsersUserIdTaxCardsTaxCardIdRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TaxCard == input.TaxCard ||
                    (this.TaxCard != null &&
                    this.TaxCard.Equals(input.TaxCard))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TaxCard != null)
                {
                    hashCode = (hashCode * 59) + this.TaxCard.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
